### ISSUE TITLE
How can one use this library to verify a signature, given the public key?

### ISSUE THREAD

**Issue by ralienpp** [GiacomoPope/dilithium-py#3]
Is it possible to use this library to verify a signature produced by another program?

I have the original data, the signature and the public key; I have not found a function like `load_pk_from_bytes(raw)`. The tests that rely on the KATs seem to be a close match, but they assume the seed and some other parameters are available - but I don't have them.

**Comment by GiacomoPope** [comment]
The input into `verify()` requires:

- a public key (encoded as bytes following the spec)
- a message to be signed (expected as bytes)
- a signature (encoded as bytes following the spec)

I would assume if you have correctly encoded public keys / signatures then `verify(pk, m, sig)` should just work.

**Comment by GiacomoPope** [comment]
@ralienpp I'll close this unless you have further questions?

**Comment by Banner-19** [comment]
How to import dilithium using python library like kyber-py?

**Comment by GiacomoPope** [comment]
You have to download the source and run it from a directory. At the moment, I purposely don't maintain a pypi module for this or Kyber-py

**Comment by Banner-19** [comment]
ok

**Comment by GiacomoPope** [comment]
I'm closing this one due to lack of responses after an explanation was given
