### ISSUE TITLE
Align ML-DSA to the finalised NIST draft

### ISSUE THREAD

**Issue by GiacomoPope** [GiacomoPope/dilithium-py#4]
https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.204.pdf

**Comment by AdityaMitra5102** [comment]
[Ignore] Adding a comment so that I get notified about the updates

**Comment by GiacomoPope** [comment]
@AdityaMitra5102 if you wanted a ping :)

**Comment by AdityaMitra5102** [comment]
Thanks a lot
