### ISSUE TITLE
URGENT REQUEST

### ISSUE THREAD

**Issue by ArkS0001** [GiacomoPope/dilithium-py#6]
Please help in implementing Dilithium, we tried all the libraries OQS is working on Colab but not on local system, we need the dilithium functionality for our project that we have to submit by next week. Please help us in integrating Dilithium, we tried your code but it is giving some relative error.
My Humble Request Please help US.
Thanking You 
Aakarshit Srivastava

**Comment by GiacomoPope** [comment]
If you need help, then share the errors or make a clearer issue, otherwise i will close this issue.

**Comment by GiacomoPope** [comment]
I'll close this. If you have an explicit issue please feel free to make a new one with more details.
